### PR TITLE
Making module aproach

### PR DESCRIPTION
**Pull request by jjalvarezl**
Making FindFruit.cmake module for cmake program to just using find_package.

### CODE REVIEW

**Comment by jjalvarezl** [comment]
I signed it!

**Comment by jjalvarezl** [comment]
I signed it!

**Comment by jjalvarezl** [comment]
Thank you @poletti-marco, I'm going to solve this issue right now, thank you for trust my solution.

**Comment by jjalvarezl** [comment]
@poletti-marco email changed and properly submited on last commit.

**Comment by poletti-marco** [comment]
Sorry about the (massive) delay. Merged now.
Thanks again for your contribution.

**Comment by jjalvarezl** [comment]
I guess that is not all. It could be improved with some additional variables, please give me some time for improve it.

**Comment by soroshsabz** [comment]
ITNOA

@poletti-marco did you any plan to create new tag and release that have this feature?

thanks

**Comment by poletti-marco** [comment]
I will definitely include this in the next release, but it might be a few
weeks from now, I'm fairly busy at the moment.

**Pull request merged**
