### PR TITLE
Use find_package(Boost)

### PR DESCRIPTION
**Pull request by tt4g**
Modern CMake uses find_package command to find libraries from the system.

#### Breaking Changes

`BOOST_DIR` no longer works. Use `Boost_INCLUDE_DIR` instead.

### CODE REVIEW

**Comment by tt4g** [comment]
`BOOST_DIR` will continue to be supported if you add the following expression:

```diff
  if(${FRUIT_USES_BOOST})
+      if(DEFINED BOOST_DIR)
+          set(Boost_INCLUDE_DIR "${BOOST_DIR}")
+      endif()
+
    find_package(Boost)
    if(Boost_FOUND)
```

But I didn't do it on purpose. That's because CMake is already used for the similar variable name `Boost_DIR`: https://cmake.org/cmake/help/latest/module/FindBoost.html#boost-cmake
`BOOST_DIR` and `Boost_DIR` are so similar that they can be confusing.

**Comment by poletti-marco** [comment]
What's the benefit of this change? I'd try to avoid breaking changes unless there's a significant benefit.

**Comment by tt4g** [comment]
`find_package (Boost)` automatically detects Boost installed in a specific path (Boost installed by CMake is reliably detected).
Users do not need to set `BOOST_DIR`.

As noted above, we can maintain compatibility by adding `set(Boost_INCLUDE_DIR "${BOOST_DIR}")`.

**Comment by poletti-marco** [comment]
> As noted above, we can maintain compatibility by adding set(Boost_INCLUDE_DIR "${BOOST_DIR}").

Yeah, let's do that then.
So that the next release can be a point release and we don't break any current setups of other Fruit users that might rely on that.

**Comment by tt4g** [comment]
Added `BOOST_DIR` support in my last commit.

**Comment by poletti-marco** [comment]
Thanks, merged this into master now.

**Pull request merged**
