### PR TITLE
Make project usable as submodule

### PR DESCRIPTION
**Pull request by cygnus9**
I added fruit as a git submodule but it failed to find the header files. With this change that does work.

### CODE REVIEW

**Comment by poletti-marco** [comment]
Hi, thanks for your contribution.
Google (my employer and copyright holder for this codebase) requires all contributors to accept a Contributor License Agreement (see the automated message above). Could you please do that and let me know?
Then I'll be happy to merge your pull request.

Btw, this is a one-time thing, so if you'll send other pull requests in the future to Fruit or any other Google project on Github you won't have to do that again.

**Comment by cygnus9** [comment]
Hi,

I accepted the CLA.

**Comment by poletti-marco** [comment]
Thanks again.
FYI, even after your second commit there was a build failure, I've fixed that in commit 55ec5fd.

**Comment by cygnus9** [comment]
Thanks.
Sorry about the build failure.

**Pull request merged**
